name: '[CD] Continuous Delivery'

on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      - name: 'Debug'
        run: 'ls -la'

      - name: 'Install Dependencies'
        run: 'npm ci'

      - name: 'Deploy to vercel (prod)'
        run: 'npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}'
